### ISSUE TITLE
Issue with runAqaArgParse.py with recent changes for custom_openj9_repo

### ISSUE THREAD

**Issue by smlambert** [adoptium/TKG#219]
See https://github.com/adoptium/aqa-tests/pull/2673#issuecomment-865497872 - message comes up after run aqa --help comment

<img width="933" alt="Screen Shot 2021-06-21 at 11 22 24 PM" src="https://user-images.githubusercontent.com/2836948/122858062-a0ae7c00-d2e7-11eb-86b6-1fd1b5296601.png">

**Comment by llxia** [comment]
This issue should be resolved if we remove runAqaConfig.json (please see adoptium/aqa-tests#3163 for details)

**Comment by llxia** [comment]
https://github.com/adoptium/aqa-tests/issues/3163 is resolved. We could use the issue to check if we have any issues without runAqaConfig.json.

Test Plan:
- use PR in aqa-tests repo, run `run aqa` with `--openj9_repo`, `--tkg_repo` and/or `--openjdk_testrepo`
- use PR in TKG repo, run `run aqa` with `--openj9_repo`, `--tkg_repo` and/or `--openjdk_testrepo`
- use PR in openj9 repo, run `run aqa` with `--openj9_repo`, `--tkg_repo` and/or `--openjdk_testrepo`

**Comment by JeromeJu** [comment]
```Traceback (most recent call last):
 File "TKG/scripts/testBot/runAqaArgParse.py", line 125, in <module>
 main()
 File "TKG/scripts/testBot/runAqaArgParse.py", line 63, in main
 with open('main/.github/workflows/runAqaConfig.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'main/.github/workflows/runAqaConfig.json'```

**Comment by JeromeJu** [comment]
Currently trying to disable the parsing of runAqaConfig.json but stuck @ https://github.com/adoptium/aqa-tests/pull/3412.

**Comment by sophia-guo** [comment]
File .github/workflows/runAqaConfig.json has been removed in both openj9 and aqa-tests repo. The problem is runAqaArgParse.py doesn't know which repo it is called. So might just update the runAqaArgParse.py with if condition. If the file doesn't exist skip it. 

To test it in the exact same workflow, i.e. PR comment, might be a little tricky. 

- create a pr in your own aqa-tests repo and comment
- update runAqa.yml with your TKG branch https://github.com/adoptium/aqa-tests/blob/master/.github/workflows/runAqa.yml#L26-L31

To test it in a simple scenario you can also just create a workflow with following steps in your own repo (different from TKG one) to see if the problem is solved or not. ( not necessarily be a comment trigger). @JeromeJu see if this helps

```
    - name: Checkout main TKG repo
      uses: actions/checkout@v2
      with: **#update to your branch and repo**
        repository: 'adoptium/TKG.git'
        ref: 'master'
        path: 'TKG'
    - name: Parse parameters
      env:
        args: ${{ github.event.comment.body }}
      run: python3 TKG/scripts/testBot/runAqaArgParse.py $args 2> log.txt
      id: argparse
```
